[project]
name = "moviesrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chainlit>=2.11.1",
    "fastapi>=0.136.3",
    "kagglehub>=1.0.1",
    "ollama>=0.6.2",
    "pandas>=3.0.3",
    "pyarrow>=24.0.0",
    "qdrant-client>=1.18.0",
    "uvicorn>=0.49.0",
]

[dependency-groups]
dev = [
    "ruff>=0.15.16",
    "ty>=0.0.48",
]
